service: app
runtime: python37

handlers:
  - url: /app/(.*\.(gif|png|jpeg|jpg|css|js|ico|svg|json|webmanifest))$
    static_files: dist/\1
    upload: dist/(.*)

  - url: /(.*)
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
